version: '3.7'

services:
  
  headcount:
    container_name: headcount   #name of the container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'